name: "sniff"
shortDesc: "Sniffing on remote kubernetes pod using ephemeral containers"
longDesc: >
  Ease the operation of sniffing on remote kubernetes pod using ephemeral containers.
  Requires Kubernetes 1.23+.
example: "kubectl sniff consul-54897664dd-gb4qg"
command: "./kubectl-sniff"
flags:
  - name: "container"
    shorthand: "c"
    desc: "Optional. Container name. Used when running multiple containers within a pod. If omitted, the first container in the pod will be chosen."
  - name: "filter"
    shorthand: "f"
    desc: "Optional. if specified, will be the tcpdump filter, otherwise no filter will be used."
  - name: "output-file"
    shorthand: "o"
    desc: "Optional. if specified, ksniff will redirect tcpdump output to local file instead of wireshark."
  - name: "tcpdump-image"
    desc: "Optional. Container image with tcpdump (default: nicolaka/netshoot:v0.14)"
  - name: "timeout"
    shorthand: "t"
    desc: "Optional. Timeout for ephemeral container to become ready (default: 1m)"
  - name: "verbose"
    shorthand: "v"
    desc: "Optional. if specified, ksniff output will include debug information"
